name: Gradle wrapper update

on:
    schedule:
        - cron: "* * * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
    update:
        runs-on: ubuntu-latest
        timeout-minutes: 15
  
        steps:
            - uses: actions/checkout@v4
            - name: set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: corretto

            - name: update gradle
              id: gradleUpdate
              uses: EdwarDDay/upgrade-gradle-action@v1

            - name: create pull request
              uses: peter-evans/create-pull-request@v3
              with:
                  commit-message: "Bump gradle to ${{ steps.gradleUpdate.outputs.gradle-version }}"
                  branch: "gradle_update/version_${{ steps.gradleUpdate.outputs.gradle-version }}"
                  delete-branch: true
                  title: "Bump gradle to ${{ steps.gradleUpdate.outputs.gradle-version }}"
                  body: |
                      ${{ steps.gradleUpdate.outputs.version-information }}
                  labels: "dependencies,gradle"
